### ISSUE TITLE
PRACTICA 5 actividad 6

### ISSUE THREAD

**Issue by Bryan080204** [SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-equipo-topicos-as#1]
https://drive.google.com/file/d/1RPFaA4HCX8ZXbjZQxv-BJ8co3C2lEgXD/view?usp=drivesdk 

REPORTE

**Comment by HECTOR-KDM02** [comment]
19 Puntos

De igual manera que la anterior mejorar la lista de figuras por lo demás todo bien

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
